language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script: python setup.py test
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#platal"
    on_success: always
    on_failure: always
    template:
      - "%{repository} : %{message} ( %{build_url} )"
